M87/force-app/main/default/objects/EventLog2__b/EventLog2__b.object-meta.xml
<CustomObject>
    <label>Event Log (BigObject)</label>
    <pluralLabel>Event Logs (BigObject)</pluralLabel>
</CustomObject>

M87/force-app/main/default/objects/EventLog2__b/fields/EventDate__c.field-meta.xml
<CustomField>
    <fullName>EventDate__c</fullName>
    <label>Event Date</label>
    <type>DateTime</type>
</CustomField>

M87/force-app/main/default/objects/EventLog2__b/fields/EventId__c.field-meta.xml
<CustomField>
    <fullName>EventId__c</fullName>
    <label>Event Id</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/EventLog2__b/fields/Info__c.field-meta.xml
<CustomField>
    <fullName>Info__c</fullName>
    <label>Info</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/EventLog2__b/fields/Quiddity__c.field-meta.xml
<CustomField>
    <fullName>Quiddity__c</fullName>
    <label>Quiddity</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/EventLog2__b/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/EventLog2__b/fields/SourceMethod__c.field-meta.xml
<CustomField>
    <fullName>SourceMethod__c</fullName>
    <label>Source Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/EventLog2__b/fields/TransactionId__c.field-meta.xml
<CustomField>
    <fullName>TransactionId__c</fullName>
    <label>TransactionId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/EventLog2__b/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <label>User Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/Log__e/fields/ExceptionTypeName__c.field-meta.xml
<CustomField>
    <fullName>ExceptionTypeName__c</fullName>
    <label>ExceptionTypeName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/Log__e/fields/Info__c.field-meta.xml
<CustomField>
    <fullName>Info__c</fullName>
    <label>Info</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/Log__e/fields/IsException__c.field-meta.xml
<CustomField>
    <fullName>IsException__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsException</label>
    <type>Checkbox</type>
</CustomField>

M87/force-app/main/default/objects/Log__e/fields/LineNumber__c.field-meta.xml
<CustomField>
    <fullName>LineNumber__c</fullName>
    <label>LineNumber</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

M87/force-app/main/default/objects/Log__e/fields/SourceClass__c.field-meta.xml
<CustomField>
    <fullName>SourceClass__c</fullName>
    <label>SourceClass</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/Log__e/fields/SourceMethod__c.field-meta.xml
<CustomField>
    <fullName>SourceMethod__c</fullName>
    <label>SourceMethod</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/Log__e/fields/TransactionId__c.field-meta.xml
<CustomField>
    <fullName>TransactionId__c</fullName>
    <label>TransactionId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/Log__e/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <label>UserId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/classes/logger/implementation/BigObjectLogStorageEntry.cls
public with sharing class BigObjectLogStorageEntry implements LogStorageEntry{
    public List<Database.SaveResult> persist(List<Log__e> logs){
        return Database.insertImmediate(toEventLog(logs));
    }
    
    private List<EventLog2__b> toEventLog(List<Log__e> logs){
        final List<EventLog2__b> eventLogs = new List<EventLog2__b>();
        for(Log__e currentLog : logs){            
            EventLog2__b eventLog = new EventLog2__b();
            eventLog.Details__c = currentLog.Details__c;
            eventLog.ExceptionTypeName__c = currentLog.ExceptionTypeName__c;
            eventLog.Info__c = currentLog.Info__c;
            eventLog.IsException__c = currentLog.IsException__c ? 1 : 0;
            eventLog.LineNumber__c = currentLog.LineNumber__c;
            eventLog.Quiddity__c = currentLog.Quiddity__c;
            eventLog.RecordId__c = currentLog.RecordId__c;
            eventLog.Severity__c = currentLog.Severity__c;
            eventLog.SourceMethod__c = currentLog.SourceMethod__c;
            eventLog.SourceClass__c = currentLog.SourceClass__c;
            eventLog.TransactionId__c = currentLog.TransactionId__c;
            eventLog.UserId__c = currentLog.UserId__c;
            eventLog.EventId__c = currentLog.ReplayId;
            eventLog.EventDate__c = currentLog.CreatedDate;

            eventLogs.add(eventLog);                  
        }

        return eventLogs;
    }
}