M87/force-app/main/default/objects/JWTAuthorization__mdt/JWTAuthorization__mdt.object-meta.xml
<CustomObject>
    <label>JWTAuthorization</label>
    <pluralLabel>JWTAuthorization</pluralLabel>
</CustomObject>

M87/force-app/main/default/objects/JWTAuthorization__mdt/fields/Audience__c.field-meta.xml
<CustomField>
    <fullName>Audience__c</fullName>
    <label>Audience</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/JWTAuthorization__mdt/fields/CertName__c.field-meta.xml
<CustomField>
    <fullName>CertName__c</fullName>
    <label>CertName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/classes/JWTAuthorization.cls
public with sharing class JWTAuthorization implements Authorization {
    private static final String JWTConfName = 'Address_fks';

    public void authorize(HttpRequest request){
        JWTAuthorization__mdt config = retrieveJWTSettings();
        if(config == null){
            throw new AuthorizationException('Configuration for JWT cannot be found.');            
        }

        Auth.JWS jws = generateJWS(config);
        Auth.JWTBearerTokenExchange bearer = new Auth.JWTBearerTokenExchange(config.Endpoint__c, jws);        
        String accessToken = bearer.getAccessToken();
        request.setHeader('Authorization', 'Bearer '+accessToken);
    }

    private JWTAuthorization__mdt retrieveJWTSettings(){
        return [SELECT MasterLabel,DeveloperName,Audience__c,CertName__c,Endpoint__c,Issuer__c,Subject__c 
            FROM JWTAuthorization__mdt WHERE DeveloperName = :JWTConfName LIMIT 1];
    }

    private Auth.JWS generateJWS(JWTAuthorization__mdt config){
        Auth.JWT jwt = new Auth.JWT();
        jwt.setSub(config.Subject__c); 
        jwt.setAud(config.Audience__c); 
        jwt.setIss(config.Issuer__c);
        return new Auth.JWS(jwt,config.CertName__c);
    }
}