M87/force-app/main/default/objects/Log__e/fields/ExceptionTypeName__c.field-meta.xml
<CustomField>
    <fullName>ExceptionTypeName__c</fullName>
    <label>ExceptionTypeName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/Log__e/fields/Info__c.field-meta.xml
<CustomField>
    <fullName>Info__c</fullName>
    <label>Info</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/Log__e/fields/IsException__c.field-meta.xml
<CustomField>
    <fullName>IsException__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsException</label>
    <type>Checkbox</type>
</CustomField>

M87/force-app/main/default/objects/Log__e/fields/LineNumber__c.field-meta.xml
<CustomField>
    <fullName>LineNumber__c</fullName>
    <label>LineNumber</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

M87/force-app/main/default/objects/Log__e/fields/SourceClass__c.field-meta.xml
<CustomField>
    <fullName>SourceClass__c</fullName>
    <label>SourceClass</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/Log__e/fields/SourceMethod__c.field-meta.xml
<CustomField>
    <fullName>SourceMethod__c</fullName>
    <label>SourceMethod</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/classes/logger/implementation/LogMappers.cls
public with sharing class LogMappers {
    
    public static Log__e mapFromException(Exception ex){
        return new FromExceptionObject().doMap(ex);
    }

    public static Log__e mapFromLogObject(Log log){
        return new FromLogObject().doMap(log);
    }

    private class FromExceptionObject {
        private Log__e doMap(Exception ex){
            Log__e eventLog = new Log__e();
            eventLog.IsException__c = true;
            eventLog.Info__c = ex.getMessage();
            eventLog.Details__c = 'Message: ' +ex.getMessage() + ', Cause: ' + ex.getCause() + ', Stack: ' +
                ex.getStackTraceString();
            eventLog.LineNumber__c = ex.getLineNumber();
            eventLog.ExceptionTypeName__c = ex.getTypeName();
            eventLog.Severity__c = LogSeverity.ERROR.name();

            return eventLog;
        }
    }

    private class FromLogObject {
        private Log__e doMap(Log currentLog){
            Log__e eventLog = new Log__e();
            eventLog.IsException__c = false;
            eventLog.Info__c = currentLog.info;
            eventLog.Details__c = currentLog.details;
            eventLog.SourceClass__c = currentLog.sourceClass?.getName();
            eventLog.SourceMethod__c = currentLog.methodName;          
            
            return eventLog;
        }
    }
}