M87/force-app/main/default/objects/Log__e/fields/Info__c.field-meta.xml
<CustomField>
    <fullName>Info__c</fullName>
    <label>Info</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/Log__e/fields/TransactionId__c.field-meta.xml
<CustomField>
    <fullName>TransactionId__c</fullName>
    <label>TransactionId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/Log__e/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <label>UserId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/classes/logger/implementation/LogValidator.cls
public with sharing class LogValidator {
    
    public Boolean areLogsValid(final List<Log__e> logs){
        for(Log__e currentLog : logs){
            if(!isLogValid(currentLog)){
                return false;
            }
        } 

        return true;
    }

    private Boolean isLogValid(final Log__e log){
        return 
            String.isNotBlank(log?.Info__c) &&
            String.isNotBlank(log?.Severity__c) &&
            String.isNotBlank(log?.TransactionId__c) && 
            String.isNotBlank(log?.UserId__c);
    }
}