M87/force-app/main/default/objects/EventLog__b/EventLog__b.object-meta.xml
<CustomObject>
    <label>Event Log</label>
    <pluralLabel>Event Logs</pluralLabel>
</CustomObject>

M87/force-app/main/default/objects/EventLog__b/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <label>Details</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

M87/force-app/main/default/objects/EventLog__b/fields/ExceptionTypeName__c.field-meta.xml
<CustomField>
    <fullName>ExceptionTypeName__c</fullName>
    <label>Exception Type Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/EventLog__b/fields/Info__c.field-meta.xml
<CustomField>
    <fullName>Info__c</fullName>
    <label>Info</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/EventLog__b/fields/IsException__c.field-meta.xml
<CustomField>
    <fullName>IsException__c</fullName>
    <label>Is Exception</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

M87/force-app/main/default/objects/EventLog__b/fields/LineNumber__c.field-meta.xml
<CustomField>
    <fullName>LineNumber__c</fullName>
    <label>Line Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

M87/force-app/main/default/objects/EventLog__b/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/EventLog__b/fields/SourceClass__c.field-meta.xml
<CustomField>
    <fullName>SourceClass__c</fullName>
    <label>Source Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/EventLog__b/fields/TransactionId__c.field-meta.xml
<CustomField>
    <fullName>TransactionId__c</fullName>
    <label>Transaction Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/Log__e/fields/ExceptionTypeName__c.field-meta.xml
<CustomField>
    <fullName>ExceptionTypeName__c</fullName>
    <label>ExceptionTypeName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/Log__e/fields/Info__c.field-meta.xml
<CustomField>
    <fullName>Info__c</fullName>
    <label>Info</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/Log__e/fields/IsException__c.field-meta.xml
<CustomField>
    <fullName>IsException__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsException</label>
    <type>Checkbox</type>
</CustomField>

M87/force-app/main/default/objects/Log__e/fields/LineNumber__c.field-meta.xml
<CustomField>
    <fullName>LineNumber__c</fullName>
    <label>LineNumber</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

M87/force-app/main/default/objects/Log__e/fields/SourceClass__c.field-meta.xml
<CustomField>
    <fullName>SourceClass__c</fullName>
    <label>SourceClass</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/Log__e/fields/SourceMethod__c.field-meta.xml
<CustomField>
    <fullName>SourceMethod__c</fullName>
    <label>SourceMethod</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/Log__e/fields/TransactionId__c.field-meta.xml
<CustomField>
    <fullName>TransactionId__c</fullName>
    <label>TransactionId</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/Log__e/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <label>UserId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/classes/logger/implementation/LogEventTriggerHandlerImp.cls
public with sharing class LogEventTriggerHandlerImp implements LogEventTriggerHandler {
    public void afterInsert(final List<Log__e> logs, final Map<Id,Log__e> logsById){        
        List<EventLog__b> bigLogs = new List<EventLog__b>();
        for(Log__e currentLog : logs){
            EventLog__b eventLog = new EventLog__b();
            eventLog.Details__c = currentLog.Details__c;
            eventLog.ExceptionTypeName__c = currentLog.ExceptionTypeName__c;
            eventLog.Info__c = currentLog.Info__c;
            eventLog.IsException__c = currentLog.IsException__c ? 1 : 0;
            eventLog.LineNumber__c = currentLog.LineNumber__c;
            eventLog.Quiddity__c = currentLog.Quiddity__c;
            eventLog.RecordId__c = currentLog.RecordId__c;
            eventLog.Severity__c = currentLog.Severity__c;
            eventLog.SourceClass__c = currentLog.SourceClass__c;
            eventLog.SourceMethod__c = currentLog.SourceMethod__c;
            eventLog.TransactionId__c = currentLog.TransactionId__c;
            eventLog.UserId__c = currentLog.UserId__c;

            bigLogs.add(eventLog);
        }

        Database.insertImmediate(bigLogs);
    }    
}