M87/force-app/main/default/objects/EventLog__c/EventLog__c.object-meta.xml
<CustomObject>
    <label>Event Log</label>
    <nameField>
        <displayFormat>AL-{0000000}</displayFormat>
        <label>EventLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

M87/force-app/main/default/objects/EventLog__c/fields/EventDate__c.field-meta.xml
<CustomField>
    <fullName>EventDate__c</fullName>
    <label>Event Date</label>
    <type>DateTime</type>
</CustomField>

M87/force-app/main/default/objects/EventLog__c/fields/EventId__c.field-meta.xml
<CustomField>
    <fullName>EventId__c</fullName>
    <label>Event Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/EventLog__c/fields/ExceptionTypeName__c.field-meta.xml
<CustomField>
    <fullName>ExceptionTypeName__c</fullName>
    <label>Exception Type Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/EventLog__c/fields/Info__c.field-meta.xml
<CustomField>
    <fullName>Info__c</fullName>
    <label>Info</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/EventLog__c/fields/Quiddity__c.field-meta.xml
<CustomField>
    <fullName>Quiddity__c</fullName>
    <label>Quiddity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ANONYMOUS</fullName>
            </value>
            <value>
                <fullName>AURA</fullName>
            </value>
            <value>
                <fullName>BATCH_ACS</fullName>
            </value>
            <value>
                <fullName>BATCH_APEX</fullName>
            </value>
            <value>
                <fullName>BATCH_CHUNK_PARALLEL</fullName>
            </value>
            <value>
                <fullName>BATCH_CHUNK_SERIAL</fullName>
            </value>
            <value>
                <fullName>BULK_API</fullName>
            </value>
            <value>
                <fullName>COMMERCE_INTEGRATION</fullName>
            </value>
            <value>
                <fullName>DISCOVERABLE_LOGIN</fullName>
            </value>
            <value>
                <fullName>FUNCTION_CALLBACK</fullName>
            </value>
            <value>
                <fullName>FUTURE</fullName>
            </value>
            <value>
                <fullName>INBOUND_EMAIL_SERVICE</fullName>
            </value>
            <value>
                <fullName>INVOCABLE_ACTION</fullName>
            </value>
            <value>
                <fullName>IOT</fullName>
            </value>
            <value>
                <fullName>QUEUEABLE</fullName>
            </value>
            <value>
                <fullName>QUICK_ACTION</fullName>
            </value>
            <value>
                <fullName>REMOTE_ACTION</fullName>
            </value>
            <value>
                <fullName>REST</fullName>
            </value>
            <value>
                <fullName>RUNTEST_ASYNC</fullName>
            </value>
            <value>
                <fullName>RUNTEST_DEPLOY</fullName>
            </value>
            <value>
                <fullName>RUNTEST_SYNC</fullName>
            </value>
            <value>
                <fullName>SCHEDULED</fullName>
            </value>
            <value>
                <fullName>SOAP</fullName>
            </value>
            <value>
                <fullName>SYNCHRONOUS</fullName>
            </value>
            <value>
                <fullName>TRANSACTION_FINALIZER_QUEUEABLE</fullName>
            </value>
            <value>
                <fullName>VF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

M87/force-app/main/default/objects/EventLog__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>FINE</fullName>
            </value>
            <value>
                <fullName>FINEST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

M87/force-app/main/default/objects/EventLog__c/fields/SourceClass__c.field-meta.xml
<CustomField>
    <fullName>SourceClass__c</fullName>
    <label>Source Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/EventLog__c/fields/SourceMethod__c.field-meta.xml
<CustomField>
    <fullName>SourceMethod__c</fullName>
    <label>Source Method</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/EventLog__c/fields/TransactionId__c.field-meta.xml
<CustomField>
    <fullName>TransactionId__c</fullName>
    <label>TransactionId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

M87/force-app/main/default/objects/EventLog__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <label>User Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

M87/force-app/test/classes/testSelectors/EventLogSelector.cls
@isTest
public with sharing class EventLogSelector {
    
    public static List<EventLog__c> selectByInfo(String info){
        return [
            SELECT 
                CreatedDate,
                Details__c,
                EventDate__c,
                EventId__c,
                Name,
                ExceptionTypeName__c,
                Info__c,
                IsException__c,
                LastModifiedById,
                LineNumber__c,
                OwnerId,
                Quiddity__c,
                RecordId__c,
                Record_Id__c,
                Severity__c,
                SourceClass__c,
                SourceMethod__c,
                TransactionId__c,
                UserId__c
            FROM EventLog__c
            WHERE Info__c = :info
        ];
    }

    public static List<EventLog__c> selectAll(){
        return [
            SELECT 
                CreatedDate,
                Details__c,
                EventDate__c,
                EventId__c,
                Name,
                ExceptionTypeName__c,
                Info__c,
                IsException__c,
                LastModifiedById,
                LineNumber__c,
                OwnerId,
                Quiddity__c,
                RecordId__c,
                Record_Id__c,
                Severity__c,
                SourceClass__c,
                SourceMethod__c,
                TransactionId__c,
                UserId__c
            FROM EventLog__c            
        ];
    }
}